site_name: Docker Swarm Rocks
site_description: Docker Swarm mode ideas and tools

site_url: https://dockerswarm.rocks
theme:
  name: material
  palette:
  - scheme: default
    primary: light blue
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  # - navigation.tabs
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: tiangolo/dockerswarm.rocks
repo_url: https://github.com/tiangolo/dockerswarm.rocks
edit_uri: ""

nav:
    - Docker Swarm Rocks: index.md
    - swarm-or-kubernetes.md
    - traefik.md
    - swarmpit.md
    - swarmprom.md
    - portainer.md
    - thelounge.md
    - gitlab-ci.md
    - Traefik v1 (previous/obsolete guides):
        - traefik-v1/index.md
        - traefik-v1/traefik.md
        - traefik-v1/traefik-technical-details.md
        - traefik-v1/traefik-with-volume.md
    - project-generators.md
    - release-notes.md

markdown_extensions:
  markdown.extensions.attr_list:
  markdown.extensions.tables:
  markdown.extensions.md_in_html:
  toc:
    permalink: true
  pymdownx.superfences:
    custom_fences:
  pymdownx.betterem:
  pymdownx.blocks.details:
  pymdownx.blocks.admonition:
    types:
    - note
    - info
    - tip
    - warning
    - danger
  pymdownx.blocks.tab:
    alternate_style: True
  mdx_include:

extra:
  analytics:
    provider: google
    property: G-DXZ6N63Y4N
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/tiangolo/dockerswarm.rocks
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/tiangolo
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/tiangolo
  - icon: fontawesome/brands/dev
    link: https://dev.to/tiangolo
  - icon: fontawesome/brands/medium
    link: https://medium.com/@tiangolo
  - icon: fontawesome/solid/globe
    link: https://tiangolo.com
